### ISSUE TITLE
module 'valinvest' has no attribute 'Fundamental'

### ISSUE THREAD

**Issue by exportio** [astro30/valinvest#6]
Followed instructions in readme.  Getting this error

AttributeError: module 'valinvest' has no attribute 'Fundamental'

Launching from Visual Studio using the following code

```
import valinvest

aapl = valinvest.Fundamental('AAPL', 'my key)
aapl.fscore()
```

**Comment by alias-noa** [comment]
from valinvest.fundamentals import Fundamental
